/*
 * JORAM: Java(TM) Open Reliable Asynchronous Messaging
 * Copyright (C) 2001 - 2004 ScalAgent Distributed Technologies
 * Copyright (C) 2004 - Bull SA
 * Copyright (C) 1996 - 2000 Dyade
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307
 * USA.
 *
 * Initial developer(s): Frederic Maistre (INRIA)
 * Contributor(s): Nicolas Tachker (Bull SA)
 *                 ScalAgent Distributed Technologies
 */
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Fri Jun 18 16:25:44 CEST 2004
//----------------------------------------------------

package org.objectweb.joram.shared.selectors;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int LONG = 28;
  public static final int AND = 16;
  public static final int IS = 24;
  public static final int LT = 12;
  public static final int PLUS = 2;
  public static final int INT = 30;
  public static final int OR = 17;
  public static final int RPAREN = 8;
  public static final int IN = 22;
  public static final int NOT = 18;
  public static final int BETWEEN = 20;
  public static final int MIN_LONG = 29;
  public static final int LPAREN = 7;
  public static final int GT = 10;
  public static final int ID = 33;
  public static final int LE = 13;
  public static final int BOOLEAN = 32;
  public static final int STRING = 34;
  public static final int COMMA = 9;
  public static final int FLOAT = 27;
  public static final int EOF = 0;
  public static final int DIVIDE = 6;
  public static final int NOTBETWEEN = 21;
  public static final int GE = 11;
  public static final int MINUS = 3;
  public static final int ESCAPE = 23;
  public static final int error = 1;
  public static final int SHORT = 31;
  public static final int LIKE = 19;
  public static final int EQ = 14;
  public static final int NULL = 25;
  public static final int NEQ = 15;
  public static final int DOUBLE = 26;
  public static final int UMINUS = 4;
}

