# Copyright (C) 1996 - 2000 BULL
# Copyright (C) 1996 - 2000 INRIA
#
# The contents of this file are subject to the Joram Public License,
# as defined by the file JORAM_LICENSE.TXT 
# 
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License on the Objectweb web site
# (www.objectweb.org). 
# 
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
# the specific terms governing rights and limitations under the License. 
# 
# The Original Code is Joram, including the java packages fr.dyade.aaa.agent,
# fr.dyade.aaa.util, fr.dyade.aaa.ip, fr.dyade.aaa.mom, and fr.dyade.aaa.joram,
# released May 24, 2000. 
# 
# The Initial Developer of the Original Code is Dyade. The Original Code and
# portions created by Dyade are Copyright Bull and Copyright INRIA.
# All Rights Reserved.
#

LIBRARIES = a3agent.jar

a3agent.jar_CLASSES = \
	NullIdException \
	UnknownAgentException \
	UnknownNotificationException \
	Debug \
	ServerDesc \
	ServiceDesc \
	A3Node \
	A3Config \
	A3Config@A3CMLHandler \
	AgentId \
	AgentId@AgentIdStamp \
	RoleMultiple \
	Notification \
	UnknownAgent \
	UnknownNotification \
	ExceptionNotification \
	Agent \
	AgentObject \
	Update \
	MatrixClock \
	MatrixClock@MatClockElt \
	Message \
	MessageQueue \
	Channel \
	Channel@TransactionChannel \
	Channel@TransientChannel \
	Engine \
	Engine@TransactionEngine \
	Engine@TransientEngine \
	AgentCreateRequest \
	AgentCreateReply \
	AgentDeleteRequest \
	AgentFactory \
	AgentFactory@AgentVector \
	AdminRequest \
	A3ServersList \
	A3ServerProperties \
	AgentAdmin \
	DriverDone \
	Driver \
	Driver@ThreadFinalizer \
	NotificationInputStream \
	NotificationOutputStream \
	FlowControlNot \
	DriverIn \
	DriverOut \
	ProxyAgent \
	ProxyAgent@DriverConnect \
	AgentDriver \
	Boot\
	Network \
	StreamNetwork \
	SingleCnxNetwork \
	SingleCnxNetwork@NetServerIn \
	SingleCnxNetwork@NetServerOut \
	SingleCnxNetwork@WatchDog \
	Server \
	AgentServer \
	ProcessEnd \
	ProcessManager \
	ProcessMonitor \
	SetField \
        SetFieldAck \
        DeleteNot \
        DeleteAck \
	DupRequest \
	DupReply \
	TransientConfig \
	TransientMessage \
	TransDriverIn \
	TransDriverIn@ObjectToNotifInputStream \
	TransDriverOut \
	TransDriverOut@ObjectToNotifOutputStream \
	TransientMonitor \
	TransientManager \
	TransientManager@TransientConnector \
	TransientServer \
	DebugDriver \
	AgentDesc \
	AdminEventListenerId \
	AdminEventReactor \
	ServerEventId \
	ServerEventReport \
	ServerEventType \
	ThreadAdmin \
	SubscribeNot \
	InputSubscribeNot \
	OutputSubscribeNot \
	StatusSubscribeNot \
	EventNot \
	MonitoringReport \
	InputReport \
	OutputReport \
	StatusReport \
	Role \
	GetStatusNot \
	PoolCnxNetwork \
	PoolCnxNetwork@StatusMessage \
	PoolCnxNetwork@NetSession \
	PoolCnxNetwork@WakeOnConnection \
	PoolCnxNetwork@NetServerOut2 \
	PoolCnxNetwork@WatchDog2 \
	StatusNot \
	HttpDriver

LIBS = a3util.jar:xerces.jar

include $(GENERAL_MK)
