# Copyright (C) 1996 - 2000 BULL
# Copyright (C) 1996 - 2000 INRIA
#
# The contents of this file are subject to the Joram Public License,
# as defined by the file JORAM_LICENSE.TXT 
# 
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License on the Objectweb web site
# (www.objectweb.org). 
# 
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
# the specific terms governing rights and limitations under the License. 
# 
# The Original Code is Joram, including the java packages fr.dyade.aaa.agent,
# fr.dyade.aaa.util, fr.dyade.aaa.ip, fr.dyade.aaa.mom, and fr.dyade.aaa.joram,
# released May 24, 2000. 
# 
# The Initial Developer of the Original Code is Dyade. The Original Code and
# portions created by Dyade are Copyright Bull and Copyright INRIA.
# All Rights Reserved.
#

PACKAGES = selectors

LIBRARIES = \
	a3mom.jar
	
a3mom.jar_CLASSES = \
	SessionItf \
	AckQueueMessageMOMExtern \
	AckTopicMessageMOMExtern \
	AckMSPMessageMOMExtern \
	BytesMessage \
	CreationWorkerQueueMOMExtern \
	CloseSubscriberMOMExtern \
	CloseTopicSessionMOMExtern \
	CloseDestinationMOMExtern \
	CreationTemporaryQueueMOMExtern \
	CreationTemporaryTopicMOMExtern \
	CreationBackDestinationMOMExtern \
	NotificationAdminDeleteDestination \
	AgentClient \
	NotificationReadOnly \
	AgentClientItf \
	NotificationReceiveSync\
	MessageAdminCreateTopic \
	MessageAdminCreateQueue \
	MessageAdminDeleteTopic \
	MessageAdminCreateSpecific \
	MessageAdminDeleteQueue \
	MessageAdminGetAgentClient \
	MessageAdminDeleteAgentClient \
	MessageAdminCleanDriver \
	MessageTransactedVector \
	MessageAckTransactedVector \
	NotificationRollback \
	MessageTransactedRollback \
	MessageAckTransactedRollback \
	MessageRollbackMOMExtern \
	CommonClientAAA\
	NotificationSubscription\
	ConnectionFactory\
	NotifMessageFromTopic\
	NotifMessageFromQueue\
	Debug\
	NotificationTopicSend\
	Destination\
	NotificationUnsubscription\
	DestinationNaming\
	NotificationUpdateSubscription\
	NotificationCloseReception\
	ExceptionMessageMOMExtern\
	ExceptionSendMessageMOMExtern \
	ExceptionListenerMOMExtern\
	ExceptionUnknownObjMOMExtern\
	Queue\
	QueueNaming\
	ClientSubscriptionKey\
	TopicSubscriptionKey\
	ReadDeliverMessageMOMExtern\
	MOMException\
	ReadOnlyMessageMOMExtern\
	ReceptionMessageMOMExtern\
	Message\
	MapMessage\
	MyByteArray\
	StreamMessage\
	RequestAgreeMOMExtern\
	RequestQueueObject\
	MessageAndAck\
	Selector\
	MessageMOMExtern\
	MessageQueueDeliverMOMExtern\
	SendingBackMessageMOMExtern\
	StateListenMessageMOMExtern\
	MessageTopicDeliverMOMExtern\
	SendingMessageQueueMOMExtern\
	SettingListenerMOMExtern\
	SettingExcListenerMOMExtern\
	NotificationAck\
	SendingMessageTopicMOMExtern\
	NotifAckFromDestination\
	TopicSubscription\
	NotificationInputMessage\
	ClientSubscription\
	NotificationMOMException\
	NotificationCloseDestination\
	SubscriptionMessageMOMExtern\
	SubscriptionNoDurableMOMExtern\
	UpdatingSubscriptionMOMExtern\
	NotificationMOMInputStream\
	ObjectMessage\
	TextMessage\
	NotificationMOMOutputStream\
	Theme\
	NotificationMOMRequest\
	Topic\
	TopicNaming\
	NotificationOutputMessage\
	UnsubscriptionMessageMOMExtern\
	NotificationQueueSend\
	NotifMessageEnumFromQueue\
	MetaData\
	MetaDataMOMExtern\
	MetaDataRequestMOMExtern\
	RecoverMsgMOMExtern\
	RecoverQueue\
	RecoverObject\
	RecoverTopic\
	NotificationRecover\
	MessageXAPrepare \
	MessageXACommit \
	MessageXARollback \
	MessageXARecover \
	MessageAckXAPrepare \
	MessageAckXACommit \
	MessageAckXARollback \
	MessageAckXARecover \
	SynchronousReceptionRequestMsg

LIBS = a3util.jar:a3agent.jar:a3ip.jar:jms.jar:joram.jar:jta-spec1_0_1.jar:jakarta-regexp-1.2.jar


include $(GENERAL_MK)
