/*
 * Copyright (C) 1996 - 2001 BULL
 * Copyright (C) 1996 - 2001 INRIA
 *
 * The contents of this file are subject to the Joram Public License,
 * as defined by the file JORAM_LICENSE.TXT 
 * 
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License on the Objectweb web site
 * (www.objectweb.org). 
 * 
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
 * the specific terms governing rights and limitations under the License. 
 * 
 * The Original Code is Joram, including the java packages fr.dyade.aaa.agent,
 * fr.dyade.aaa.util, fr.dyade.aaa.ip, fr.dyade.aaa.mom, fr.dyade.aaa.jndi and 
 * fr.dyade.aaa.joram, released May 24, 2000. 
 * 
 * The Initial Developer of the Original Code is Dyade. The Original Code and
 * portions created by Dyade are Copyright Bull and Copyright INRIA.
 * All Rights Reserved.
 */

//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Thu Jul 26 09:01:26 CEST 2001
//----------------------------------------------------

package fr.dyade.aaa.mom.selectors;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int AND = 16;
  public static final int IS = 24;
  public static final int LT = 12;
  public static final int PLUS = 2;
  public static final int OR = 17;
  public static final int RPAREN = 8;
  public static final int IN = 22;
  public static final int NOT = 18;
  public static final int BETWEEN = 20;
  public static final int LPAREN = 7;
  public static final int GT = 10;
  public static final int ID = 28;
  public static final int LE = 13;
  public static final int BOOLEAN = 27;
  public static final int STRING = 29;
  public static final int COMMA = 9;
  public static final int EOF = 0;
  public static final int DIVIDE = 6;
  public static final int NOTBETWEEN = 21;
  public static final int GE = 11;
  public static final int MINUS = 3;
  public static final int ESCAPE = 23;
  public static final int error = 1;
  public static final int LIKE = 19;
  public static final int EQ = 14;
  public static final int NULL = 25;
  public static final int NEQ = 15;
  public static final int DOUBLE = 26;
  public static final int UMINUS = 4;
}

