<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="joram"
    nsURI="http:///joram.ow2.org/ecore/joram" nsPrefix="joram">
  <eClassifiers xsi:type="ecore:EClass" name="Config">
    <eStructuralFeatures xsi:type="ecore:EReference" name="servers" upperBound="-1"
        eType="#//ScalAgentServer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domains" upperBound="-1"
        eType="#//NetworkDomain" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hosts" upperBound="-1"
        eType="#//Host" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" eType="#//ConfigProperties"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Host">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="localhost"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="login" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="privateKeyPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shell" eType="#//Shell"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="protocol" eType="#//Protocol"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transfert" eType="#//Transfert"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Shell">
    <eLiterals name="SH"/>
    <eLiterals name="CSH" value="1"/>
    <eLiterals name="WinCommand" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Protocol">
    <eLiterals name="OpenSSH"/>
    <eLiterals name="SSH" value="1"/>
    <eLiterals name="JSSH" value="2"/>
    <eLiterals name="ApacheTelnet" value="3"/>
    <eLiterals name="JTelnet" value="4"/>
    <eLiterals name="ExternalTelnet" value="5"/>
    <eLiterals name="PLINK" value="6"/>
    <eLiterals name="LOCAL_SH" value="7"/>
    <eLiterals name="LOCAL_CSH" value="8"/>
    <eLiterals name="LOCAL_WIN" value="9"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Transfert">
    <eLiterals name="JSCP"/>
    <eLiterals name="SCP" value="1"/>
    <eLiterals name="PSCP" value="2"/>
    <eLiterals name="JSFTP" value="3"/>
    <eLiterals name="Apache_FTP" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScalAgentServer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="JORAM"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="#//JoramService" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="host" lowerBound="1" eType="#//Host"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="StorageDirectory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="network" upperBound="-1"
        eType="#//NetworkPort" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JORAM" eSuperTypes="#//ScalAgentServer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="jmsObjects" upperBound="-1"
        eType="#//JMSObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="JoramVersion">
    <eLiterals name="JORAM_5_3_0" value="530" literal="5.3.0"/>
    <eLiterals name="JORAM_5_2_6" value="526" literal="5.2.6"/>
    <eLiterals name="JORAM_5_2_5" value="525" literal="5.2.5"/>
    <eLiterals name="JORAM_5_2_4" value="524" literal="5.2.4"/>
    <eLiterals name="JORAM_5_2_3" value="523" literal="5.2.3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JoramService" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdminProxy" eSuperTypes="#//JoramService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="AdminProxy"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="8091"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionManager" eSuperTypes="#//JoramService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="user" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="root"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="root"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="ConnectionManager"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JNDIServer" eSuperTypes="#//JoramService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="JNDIServer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="16400"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DistributedJNDIServer" eSuperTypes="#//JoramService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="DistributedJNDIServer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="16400"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="knownServers" upperBound="-1"
        eType="#//ScalAgentServer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TCPProxyService" eSuperTypes="#//JoramService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="TCPProxyService"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="16010"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomService" eSuperTypes="#//JoramService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="args" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkDomain">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="D0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="network" eType="#//Network"
        defaultValueLiteral="fr.dyade.aaa.agent.PoolNetwork"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkPort">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="16100"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domain" eType="#//NetworkDomain"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JMSObject" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Destination" abstract="true" eSuperTypes="#//JMSObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="readers" upperBound="-1"
        eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="writers" upperBound="-1"
        eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="freeReader" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="freeWriter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jndiName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Queue" eSuperTypes="#//Destination">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="queue"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="org.objectweb.joram.mom.dest.Queue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deadMessageQueue" eType="#//Queue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Topic" eSuperTypes="#//Destination">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="topic"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="org.objectweb.joram.mom.dest.Topic"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User" eSuperTypes="#//JMSObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="anonymous" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="anonymous"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionFactory" eSuperTypes="#//JMSObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" eType="#//ConnectionFactoryClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jndiName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="cf"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConnectionFactoryClass">
    <eLiterals name="TcpConnectionFactory" literal="org.objectweb.joram.client.jms.tcp.TcpConnectionFactory"/>
    <eLiterals name="SoapConnectionFactory" value="1" literal="org.objectweb.joram.client.jms.soap.SoapConnectionFactory"/>
    <eLiterals name="LocalConnectionFactory" value="2" literal="org.objectweb.joram.client.jms.local.LocalConnectionFactory"/>
    <eLiterals name="PooledConnectionFactory" value="3" literal="org.objectweb.joram.client.jms.pool.PooledConnectionFactory"/>
    <eLiterals name="HATcpConnectionFactory" value="4" literal="org.objectweb.joram.client.jms.ha.tcp.HATcpConnectionFactory"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Transaction">
    <eLiterals name="NTransaction" literal="fr.dyade.aaa.util.NTransaction"/>
    <eLiterals name="NGTransaction" value="1" literal="fr.dyade.aaa.util.NGTransaction"/>
    <eLiterals name="JTransaction" value="2" literal="fr.dyade.aaa.util.JTransaction"/>
    <eLiterals name="ATransaction" value="3" literal="fr.dyade.aaa.util.ATransaction"/>
    <eLiterals name="NullTransaction" value="4" literal="fr.dyade.aaa.util.NullTransaction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Network">
    <eLiterals name="PoolNetwork" literal="fr.dyade.aaa.agent.PoolNetwork"/>
    <eLiterals name="SimpleNetwork" value="1" literal="fr.dyade.aaa.agent.SimpleNetwork"/>
    <eLiterals name="NGNetwork" value="2" literal="fr.dyade.aaa.agent.NGNetwork"/>
    <eLiterals name="HttpNetwork" value="3" literal="fr.dyade.aaa.agent.HttpNetwork"/>
    <eLiterals name="HttpsNetwork" value="4" literal="fr.dyade.aaa.agent.HttpsNetwork"/>
    <eLiterals name="SSLNetwork" value="5" literal="fr.dyade.aaa.agent.SSLNetwork"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigProperties">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CustomProperty" eSuperTypes="#//Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="name"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PoolNetworkProperties" eSuperTypes="#//Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbMaxCnx" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="compressedFlows" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxMessageInFlow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IdleTimeout" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="60000"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HttpNetworkProperties" eSuperTypes="#//Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activationPeriod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="10000"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbDaemon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkProperties" eSuperTypes="#//Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="backlog" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="5"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CnxRetry" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="3"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TcpNoDelay" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SoLinger" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SoTimeout" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ConnectTimeout" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NTransactionProperties" eSuperTypes="#//Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NTLogMemorySize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="2048"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NTLogFileSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="16"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NTNoLockFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NTLogThresholdOperation"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1000"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NTLogMemoryCapacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="4096"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransactionProperty" eSuperTypes="#//Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transaction" eType="#//Transaction"
        defaultValueLiteral=""/>
  </eClassifiers>
</ecore:EPackage>
